#!/bin/sh

# general
alias s="sudo"
alias v=$EDITOR
alias sv="sudo -e"
alias stow="stow -t ~/ -v"
alias la="ls -hla --color=auto --group-directories-first"
alias lsblk="lsblk | grep -v '^loop'"
alias gdc="git commit -m \"minor changes\""

# pacman
#alias pm="sudo pacman"
#alias pmi="sudo pacman -S"
#alias pmu="sudo pacman -Syu"
#alias pmr="sudo pacman -Rns"
#alias pmro="sudo pacman -Rs $(pacman -Qqtd)"

# apt
#alias pm="sudo apt"
#alias pmi="sudo apt install"
#alias pmu="sudo apt update && sudo apt upgrade"
#alias pmr="sudo apt autoremove"
#alias pms="sudo apt search"

# dnf
alias pm="sudo dnf"
alias pmi="sudo dnf install"
alias pmu="sudo dnf update"
alias pmr="sudo dnf remove"
alias pms="sudo dnf search"

# zypper
#alias zp="sudo zypper"

# soystemd
alias off="systemctl poweroff"
alias reb="systemctl reboot"
alias susp="systemctl suspend"
alias uefi="systemctl reboot --firmware-setup"
