#!/bin/sh

# prefer neovim to vim if present


## general
alias \
s="sudo" \
v=${EDITOR} \
sv="sudo ${EDITOR}" \
stow="stow -t ~/ -v --ignore '.DS_Store' --ignore '.git'" \
wttr="curl https://www.wttr.in" \
la="ls -Galh"

## pacman
# alias \
# p="sudo pacman" \
# upg="sudo pacman -Syu" \

## apt
# alias \
# ap="sudo apt" \
# upg="sudo apt update && sudo apt upgrade" \

## soystemd 
# alias \
# off="systemctl poweroff" \
# reb="systemctl reboot" \
# susp="systemctl suspend" \
# bios="systemctl reboot --firmware-setup"