#!/bin/sh

## general
alias s="sudo"
alias v=$EDITOR
alias sv="sudo -e"
alias stow="stow -t ~/ -v"
alias la="ls -hla --color=auto --group-directories-first"
alias lsblk="lsblk | grep -v '^loop'"
## pacman
# alias p="sudo pacman"
# alias upg="sudo pacman -Syu"

## apt
alias ap="sudo apt"
alias upg="sudo apt update && sudo apt upgrade; flatpak update; sudo snap refresh"

## soystemd
alias off="systemctl poweroff"
alias reb="systemctl reboot"
alias susp="systemctl suspend"
alias bios="systemctl reboot --firmware-setup"
